### ISSUE TITLE
Inquiry on Utilizing Your Trained Model for Molecule Generation in Protein Pockets

### ISSUE THREAD

**Issue by gibhdyw** [WonhoZhung/DeepICL#2]
Hello,Thank you for sharing your excellent work! Could you please guide me on how to use your trained model to generate molecules for my protein pockets?

Best regards

**Comment by WonhoZhung** [comment]
Hello, thank you for reaching out our work. First, you need to process your protein `.pdb` file into processed data `.pkl` file with `processor.py`, then use `generate.py` to sample molecules. You may follow the Google Colab Demo of scaffold elaboration example for applying to your pocket.
