### ISSUE TITLE
How to generate molecules without reference ligand?

### ISSUE THREAD

**Issue by xiangwenkai** [WonhoZhung/DeepICL#3]
Hello, thank you for your excellent work! The demo you provided requires a ligand file. Could you please explain how to generate molecules without a reference ligand, as mentioned in your paper under "de novo ligand design"?

**Comment by WonhoZhung** [comment]
Thanks for reaching out and your interest in our work.
And I apologize for the late reply.
I updated the code and provide a google colab demo for generating ligand molecules without a reference ligand.
Hope the demo provides you a sufficient instruction.

https://drive.google.com/file/d/1Sg2mIeFut66KjAhZBgM-1nPqSmc9g7lC/view?usp=sharing
